/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.FlowSetRequest;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthenticatorDuoStageRequest
 */
public class AuthenticatorDuoStageRequestTest {
    private final AuthenticatorDuoStageRequest model = new AuthenticatorDuoStageRequest();

    /**
     * Model tests for AuthenticatorDuoStageRequest
     */
    @Test
    public void testAuthenticatorDuoStageRequest() {
        // TODO: test AuthenticatorDuoStageRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'flowSet'
     */
    @Test
    public void flowSetTest() {
        // TODO: test flowSet
    }

    /**
     * Test the property 'configureFlow'
     */
    @Test
    public void configureFlowTest() {
        // TODO: test configureFlow
    }

    /**
     * Test the property 'friendlyName'
     */
    @Test
    public void friendlyNameTest() {
        // TODO: test friendlyName
    }

    /**
     * Test the property 'clientId'
     */
    @Test
    public void clientIdTest() {
        // TODO: test clientId
    }

    /**
     * Test the property 'clientSecret'
     */
    @Test
    public void clientSecretTest() {
        // TODO: test clientSecret
    }

    /**
     * Test the property 'apiHostname'
     */
    @Test
    public void apiHostnameTest() {
        // TODO: test apiHostname
    }

    /**
     * Test the property 'adminIntegrationKey'
     */
    @Test
    public void adminIntegrationKeyTest() {
        // TODO: test adminIntegrationKey
    }

    /**
     * Test the property 'adminSecretKey'
     */
    @Test
    public void adminSecretKeyTest() {
        // TODO: test adminSecretKey
    }

}
