/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.AuthenticatorAttachmentEnum;
import org.openapitools.client.model.FlowSetRequest;
import org.openapitools.client.model.ResidentKeyRequirementEnum;
import org.openapitools.client.model.UserVerificationEnum;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthenticatorWebAuthnStageRequest
 */
public class AuthenticatorWebAuthnStageRequestTest {
    private final AuthenticatorWebAuthnStageRequest model = new AuthenticatorWebAuthnStageRequest();

    /**
     * Model tests for AuthenticatorWebAuthnStageRequest
     */
    @Test
    public void testAuthenticatorWebAuthnStageRequest() {
        // TODO: test AuthenticatorWebAuthnStageRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'flowSet'
     */
    @Test
    public void flowSetTest() {
        // TODO: test flowSet
    }

    /**
     * Test the property 'configureFlow'
     */
    @Test
    public void configureFlowTest() {
        // TODO: test configureFlow
    }

    /**
     * Test the property 'friendlyName'
     */
    @Test
    public void friendlyNameTest() {
        // TODO: test friendlyName
    }

    /**
     * Test the property 'userVerification'
     */
    @Test
    public void userVerificationTest() {
        // TODO: test userVerification
    }

    /**
     * Test the property 'authenticatorAttachment'
     */
    @Test
    public void authenticatorAttachmentTest() {
        // TODO: test authenticatorAttachment
    }

    /**
     * Test the property 'residentKeyRequirement'
     */
    @Test
    public void residentKeyRequirementTest() {
        // TODO: test residentKeyRequirement
    }

    /**
     * Test the property 'deviceTypeRestrictions'
     */
    @Test
    public void deviceTypeRestrictionsTest() {
        // TODO: test deviceTypeRestrictions
    }

}
