/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AuthenticatedSessionUserAgentDevice;
import org.openapitools.client.model.AuthenticatedSessionUserAgentOs;
import org.openapitools.client.model.AuthenticatedSessionUserAgentUserAgent;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AuthenticatedSessionUserAgent
 */
public class AuthenticatedSessionUserAgentTest {
    private final AuthenticatedSessionUserAgent model = new AuthenticatedSessionUserAgent();

    /**
     * Model tests for AuthenticatedSessionUserAgent
     */
    @Test
    public void testAuthenticatedSessionUserAgent() {
        // TODO: test AuthenticatedSessionUserAgent
    }

    /**
     * Test the property 'device'
     */
    @Test
    public void deviceTest() {
        // TODO: test device
    }

    /**
     * Test the property 'os'
     */
    @Test
    public void osTest() {
        // TODO: test os
    }

    /**
     * Test the property 'userAgent'
     */
    @Test
    public void userAgentTest() {
        // TODO: test userAgent
    }

    /**
     * Test the property 'string'
     */
    @Test
    public void stringTest() {
        // TODO: test string
    }

}
