/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExtraRoleObjectPermission
 */
public class ExtraRoleObjectPermissionTest {
    private final ExtraRoleObjectPermission model = new ExtraRoleObjectPermission();

    /**
     * Model tests for ExtraRoleObjectPermission
     */
    @Test
    public void testExtraRoleObjectPermission() {
        // TODO: test ExtraRoleObjectPermission
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'codename'
     */
    @Test
    public void codenameTest() {
        // TODO: test codename
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'appLabel'
     */
    @Test
    public void appLabelTest() {
        // TODO: test appLabel
    }

    /**
     * Test the property 'objectPk'
     */
    @Test
    public void objectPkTest() {
        // TODO: test objectPk
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'appLabelVerbose'
     */
    @Test
    public void appLabelVerboseTest() {
        // TODO: test appLabelVerbose
    }

    /**
     * Test the property 'modelVerbose'
     */
    @Test
    public void modelVerboseTest() {
        // TODO: test modelVerbose
    }

    /**
     * Test the property 'objectDescription'
     */
    @Test
    public void objectDescriptionTest() {
        // TODO: test objectDescription
    }

}
