/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.OutgoingSyncDeleteAction;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleWorkspaceProvider
 */
public class GoogleWorkspaceProviderTest {
    private final GoogleWorkspaceProvider model = new GoogleWorkspaceProvider();

    /**
     * Model tests for GoogleWorkspaceProvider
     */
    @Test
    public void testGoogleWorkspaceProvider() {
        // TODO: test GoogleWorkspaceProvider
    }

    /**
     * Test the property 'pk'
     */
    @Test
    public void pkTest() {
        // TODO: test pk
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'propertyMappings'
     */
    @Test
    public void propertyMappingsTest() {
        // TODO: test propertyMappings
    }

    /**
     * Test the property 'propertyMappingsGroup'
     */
    @Test
    public void propertyMappingsGroupTest() {
        // TODO: test propertyMappingsGroup
    }

    /**
     * Test the property 'component'
     */
    @Test
    public void componentTest() {
        // TODO: test component
    }

    /**
     * Test the property 'assignedBackchannelApplicationSlug'
     */
    @Test
    public void assignedBackchannelApplicationSlugTest() {
        // TODO: test assignedBackchannelApplicationSlug
    }

    /**
     * Test the property 'assignedBackchannelApplicationName'
     */
    @Test
    public void assignedBackchannelApplicationNameTest() {
        // TODO: test assignedBackchannelApplicationName
    }

    /**
     * Test the property 'verboseName'
     */
    @Test
    public void verboseNameTest() {
        // TODO: test verboseName
    }

    /**
     * Test the property 'verboseNamePlural'
     */
    @Test
    public void verboseNamePluralTest() {
        // TODO: test verboseNamePlural
    }

    /**
     * Test the property 'metaModelName'
     */
    @Test
    public void metaModelNameTest() {
        // TODO: test metaModelName
    }

    /**
     * Test the property 'delegatedSubject'
     */
    @Test
    public void delegatedSubjectTest() {
        // TODO: test delegatedSubject
    }

    /**
     * Test the property 'credentials'
     */
    @Test
    public void credentialsTest() {
        // TODO: test credentials
    }

    /**
     * Test the property 'scopes'
     */
    @Test
    public void scopesTest() {
        // TODO: test scopes
    }

    /**
     * Test the property 'excludeUsersServiceAccount'
     */
    @Test
    public void excludeUsersServiceAccountTest() {
        // TODO: test excludeUsersServiceAccount
    }

    /**
     * Test the property 'filterGroup'
     */
    @Test
    public void filterGroupTest() {
        // TODO: test filterGroup
    }

    /**
     * Test the property 'userDeleteAction'
     */
    @Test
    public void userDeleteActionTest() {
        // TODO: test userDeleteAction
    }

    /**
     * Test the property 'groupDeleteAction'
     */
    @Test
    public void groupDeleteActionTest() {
        // TODO: test groupDeleteAction
    }

    /**
     * Test the property 'defaultGroupEmailDomain'
     */
    @Test
    public void defaultGroupEmailDomainTest() {
        // TODO: test defaultGroupEmailDomain
    }

}
