/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.client.model.PolicyEngineMode;
import org.openapitools.client.model.UserMatchingModeEnum;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LDAPSource
 */
public class LDAPSourceTest {
    private final LDAPSource model = new LDAPSource();

    /**
     * Model tests for LDAPSource
     */
    @Test
    public void testLDAPSource() {
        // TODO: test LDAPSource
    }

    /**
     * Test the property 'pk'
     */
    @Test
    public void pkTest() {
        // TODO: test pk
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'authenticationFlow'
     */
    @Test
    public void authenticationFlowTest() {
        // TODO: test authenticationFlow
    }

    /**
     * Test the property 'enrollmentFlow'
     */
    @Test
    public void enrollmentFlowTest() {
        // TODO: test enrollmentFlow
    }

    /**
     * Test the property 'component'
     */
    @Test
    public void componentTest() {
        // TODO: test component
    }

    /**
     * Test the property 'verboseName'
     */
    @Test
    public void verboseNameTest() {
        // TODO: test verboseName
    }

    /**
     * Test the property 'verboseNamePlural'
     */
    @Test
    public void verboseNamePluralTest() {
        // TODO: test verboseNamePlural
    }

    /**
     * Test the property 'metaModelName'
     */
    @Test
    public void metaModelNameTest() {
        // TODO: test metaModelName
    }

    /**
     * Test the property 'policyEngineMode'
     */
    @Test
    public void policyEngineModeTest() {
        // TODO: test policyEngineMode
    }

    /**
     * Test the property 'userMatchingMode'
     */
    @Test
    public void userMatchingModeTest() {
        // TODO: test userMatchingMode
    }

    /**
     * Test the property 'managed'
     */
    @Test
    public void managedTest() {
        // TODO: test managed
    }

    /**
     * Test the property 'userPathTemplate'
     */
    @Test
    public void userPathTemplateTest() {
        // TODO: test userPathTemplate
    }

    /**
     * Test the property 'icon'
     */
    @Test
    public void iconTest() {
        // TODO: test icon
    }

    /**
     * Test the property 'serverUri'
     */
    @Test
    public void serverUriTest() {
        // TODO: test serverUri
    }

    /**
     * Test the property 'peerCertificate'
     */
    @Test
    public void peerCertificateTest() {
        // TODO: test peerCertificate
    }

    /**
     * Test the property 'clientCertificate'
     */
    @Test
    public void clientCertificateTest() {
        // TODO: test clientCertificate
    }

    /**
     * Test the property 'bindCn'
     */
    @Test
    public void bindCnTest() {
        // TODO: test bindCn
    }

    /**
     * Test the property 'startTls'
     */
    @Test
    public void startTlsTest() {
        // TODO: test startTls
    }

    /**
     * Test the property 'sni'
     */
    @Test
    public void sniTest() {
        // TODO: test sni
    }

    /**
     * Test the property 'baseDn'
     */
    @Test
    public void baseDnTest() {
        // TODO: test baseDn
    }

    /**
     * Test the property 'additionalUserDn'
     */
    @Test
    public void additionalUserDnTest() {
        // TODO: test additionalUserDn
    }

    /**
     * Test the property 'additionalGroupDn'
     */
    @Test
    public void additionalGroupDnTest() {
        // TODO: test additionalGroupDn
    }

    /**
     * Test the property 'userObjectFilter'
     */
    @Test
    public void userObjectFilterTest() {
        // TODO: test userObjectFilter
    }

    /**
     * Test the property 'groupObjectFilter'
     */
    @Test
    public void groupObjectFilterTest() {
        // TODO: test groupObjectFilter
    }

    /**
     * Test the property 'groupMembershipField'
     */
    @Test
    public void groupMembershipFieldTest() {
        // TODO: test groupMembershipField
    }

    /**
     * Test the property 'objectUniquenessField'
     */
    @Test
    public void objectUniquenessFieldTest() {
        // TODO: test objectUniquenessField
    }

    /**
     * Test the property 'passwordLoginUpdateInternalPassword'
     */
    @Test
    public void passwordLoginUpdateInternalPasswordTest() {
        // TODO: test passwordLoginUpdateInternalPassword
    }

    /**
     * Test the property 'syncUsers'
     */
    @Test
    public void syncUsersTest() {
        // TODO: test syncUsers
    }

    /**
     * Test the property 'syncUsersPassword'
     */
    @Test
    public void syncUsersPasswordTest() {
        // TODO: test syncUsersPassword
    }

    /**
     * Test the property 'syncGroups'
     */
    @Test
    public void syncGroupsTest() {
        // TODO: test syncGroups
    }

    /**
     * Test the property 'syncParentGroup'
     */
    @Test
    public void syncParentGroupTest() {
        // TODO: test syncParentGroup
    }

    /**
     * Test the property 'propertyMappings'
     */
    @Test
    public void propertyMappingsTest() {
        // TODO: test propertyMappings
    }

    /**
     * Test the property 'propertyMappingsGroup'
     */
    @Test
    public void propertyMappingsGroupTest() {
        // TODO: test propertyMappingsGroup
    }

    /**
     * Test the property 'connectivity'
     */
    @Test
    public void connectivityTest() {
        // TODO: test connectivity
    }

}
