/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OAuth2ProviderSetupURLs
 */
public class OAuth2ProviderSetupURLsTest {
    private final OAuth2ProviderSetupURLs model = new OAuth2ProviderSetupURLs();

    /**
     * Model tests for OAuth2ProviderSetupURLs
     */
    @Test
    public void testOAuth2ProviderSetupURLs() {
        // TODO: test OAuth2ProviderSetupURLs
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'authorize'
     */
    @Test
    public void authorizeTest() {
        // TODO: test authorize
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'userInfo'
     */
    @Test
    public void userInfoTest() {
        // TODO: test userInfo
    }

    /**
     * Test the property 'providerInfo'
     */
    @Test
    public void providerInfoTest() {
        // TODO: test providerInfo
    }

    /**
     * Test the property 'logout'
     */
    @Test
    public void logoutTest() {
        // TODO: test logout
    }

    /**
     * Test the property 'jwks'
     */
    @Test
    public void jwksTest() {
        // TODO: test jwks
    }

}
