/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PasswordExpiryPolicyRequest
 */
public class PasswordExpiryPolicyRequestTest {
    private final PasswordExpiryPolicyRequest model = new PasswordExpiryPolicyRequest();

    /**
     * Model tests for PasswordExpiryPolicyRequest
     */
    @Test
    public void testPasswordExpiryPolicyRequest() {
        // TODO: test PasswordExpiryPolicyRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'executionLogging'
     */
    @Test
    public void executionLoggingTest() {
        // TODO: test executionLogging
    }

    /**
     * Test the property 'days'
     */
    @Test
    public void daysTest() {
        // TODO: test days
    }

    /**
     * Test the property 'denyOnly'
     */
    @Test
    public void denyOnlyTest() {
        // TODO: test denyOnly
    }

}
