/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PatchedDummyPolicyRequest
 */
public class PatchedDummyPolicyRequestTest {
    private final PatchedDummyPolicyRequest model = new PatchedDummyPolicyRequest();

    /**
     * Model tests for PatchedDummyPolicyRequest
     */
    @Test
    public void testPatchedDummyPolicyRequest() {
        // TODO: test PatchedDummyPolicyRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'executionLogging'
     */
    @Test
    public void executionLoggingTest() {
        // TODO: test executionLogging
    }

    /**
     * Test the property 'result'
     */
    @Test
    public void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'waitMin'
     */
    @Test
    public void waitMinTest() {
        // TODO: test waitMin
    }

    /**
     * Test the property 'waitMax'
     */
    @Test
    public void waitMaxTest() {
        // TODO: test waitMax
    }

}
