/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UserMatchingModeEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PatchedSCIMSourceRequest
 */
public class PatchedSCIMSourceRequestTest {
    private final PatchedSCIMSourceRequest model = new PatchedSCIMSourceRequest();

    /**
     * Model tests for PatchedSCIMSourceRequest
     */
    @Test
    public void testPatchedSCIMSourceRequest() {
        // TODO: test PatchedSCIMSourceRequest
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'userMatchingMode'
     */
    @Test
    public void userMatchingModeTest() {
        // TODO: test userMatchingMode
    }

    /**
     * Test the property 'userPathTemplate'
     */
    @Test
    public void userPathTemplateTest() {
        // TODO: test userPathTemplate
    }

}
