/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.DigestAlgorithmEnum;
import org.openapitools.client.model.SignatureAlgorithmEnum;
import org.openapitools.client.model.SpBindingEnum;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SAMLProvider
 */
public class SAMLProviderTest {
    private final SAMLProvider model = new SAMLProvider();

    /**
     * Model tests for SAMLProvider
     */
    @Test
    public void testSAMLProvider() {
        // TODO: test SAMLProvider
    }

    /**
     * Test the property 'pk'
     */
    @Test
    public void pkTest() {
        // TODO: test pk
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'authenticationFlow'
     */
    @Test
    public void authenticationFlowTest() {
        // TODO: test authenticationFlow
    }

    /**
     * Test the property 'authorizationFlow'
     */
    @Test
    public void authorizationFlowTest() {
        // TODO: test authorizationFlow
    }

    /**
     * Test the property 'propertyMappings'
     */
    @Test
    public void propertyMappingsTest() {
        // TODO: test propertyMappings
    }

    /**
     * Test the property 'component'
     */
    @Test
    public void componentTest() {
        // TODO: test component
    }

    /**
     * Test the property 'assignedApplicationSlug'
     */
    @Test
    public void assignedApplicationSlugTest() {
        // TODO: test assignedApplicationSlug
    }

    /**
     * Test the property 'assignedApplicationName'
     */
    @Test
    public void assignedApplicationNameTest() {
        // TODO: test assignedApplicationName
    }

    /**
     * Test the property 'assignedBackchannelApplicationSlug'
     */
    @Test
    public void assignedBackchannelApplicationSlugTest() {
        // TODO: test assignedBackchannelApplicationSlug
    }

    /**
     * Test the property 'assignedBackchannelApplicationName'
     */
    @Test
    public void assignedBackchannelApplicationNameTest() {
        // TODO: test assignedBackchannelApplicationName
    }

    /**
     * Test the property 'verboseName'
     */
    @Test
    public void verboseNameTest() {
        // TODO: test verboseName
    }

    /**
     * Test the property 'verboseNamePlural'
     */
    @Test
    public void verboseNamePluralTest() {
        // TODO: test verboseNamePlural
    }

    /**
     * Test the property 'metaModelName'
     */
    @Test
    public void metaModelNameTest() {
        // TODO: test metaModelName
    }

    /**
     * Test the property 'acsUrl'
     */
    @Test
    public void acsUrlTest() {
        // TODO: test acsUrl
    }

    /**
     * Test the property 'audience'
     */
    @Test
    public void audienceTest() {
        // TODO: test audience
    }

    /**
     * Test the property 'issuer'
     */
    @Test
    public void issuerTest() {
        // TODO: test issuer
    }

    /**
     * Test the property 'assertionValidNotBefore'
     */
    @Test
    public void assertionValidNotBeforeTest() {
        // TODO: test assertionValidNotBefore
    }

    /**
     * Test the property 'assertionValidNotOnOrAfter'
     */
    @Test
    public void assertionValidNotOnOrAfterTest() {
        // TODO: test assertionValidNotOnOrAfter
    }

    /**
     * Test the property 'sessionValidNotOnOrAfter'
     */
    @Test
    public void sessionValidNotOnOrAfterTest() {
        // TODO: test sessionValidNotOnOrAfter
    }

    /**
     * Test the property 'nameIdMapping'
     */
    @Test
    public void nameIdMappingTest() {
        // TODO: test nameIdMapping
    }

    /**
     * Test the property 'digestAlgorithm'
     */
    @Test
    public void digestAlgorithmTest() {
        // TODO: test digestAlgorithm
    }

    /**
     * Test the property 'signatureAlgorithm'
     */
    @Test
    public void signatureAlgorithmTest() {
        // TODO: test signatureAlgorithm
    }

    /**
     * Test the property 'signingKp'
     */
    @Test
    public void signingKpTest() {
        // TODO: test signingKp
    }

    /**
     * Test the property 'verificationKp'
     */
    @Test
    public void verificationKpTest() {
        // TODO: test verificationKp
    }

    /**
     * Test the property 'spBinding'
     */
    @Test
    public void spBindingTest() {
        // TODO: test spBinding
    }

    /**
     * Test the property 'defaultRelayState'
     */
    @Test
    public void defaultRelayStateTest() {
        // TODO: test defaultRelayState
    }

    /**
     * Test the property 'urlDownloadMetadata'
     */
    @Test
    public void urlDownloadMetadataTest() {
        // TODO: test urlDownloadMetadata
    }

    /**
     * Test the property 'urlSsoPost'
     */
    @Test
    public void urlSsoPostTest() {
        // TODO: test urlSsoPost
    }

    /**
     * Test the property 'urlSsoRedirect'
     */
    @Test
    public void urlSsoRedirectTest() {
        // TODO: test urlSsoRedirect
    }

    /**
     * Test the property 'urlSsoInit'
     */
    @Test
    public void urlSsoInitTest() {
        // TODO: test urlSsoInit
    }

    /**
     * Test the property 'urlSloPost'
     */
    @Test
    public void urlSloPostTest() {
        // TODO: test urlSloPost
    }

    /**
     * Test the property 'urlSloRedirect'
     */
    @Test
    public void urlSloRedirectTest() {
        // TODO: test urlSloRedirect
    }

}
