/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.CapabilitiesEnum;
import org.openapitools.client.model.ErrorReportingConfig;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Serialize authentik Config into DRF Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-25T23:12:57.050901581-03:00[America/Argentina/Cordoba]", comments = "Generator version: 7.8.0")
public class Config {
  public static final String SERIALIZED_NAME_ERROR_REPORTING = "error_reporting";
  @SerializedName(SERIALIZED_NAME_ERROR_REPORTING)
  private ErrorReportingConfig errorReporting;

  public static final String SERIALIZED_NAME_CAPABILITIES = "capabilities";
  @SerializedName(SERIALIZED_NAME_CAPABILITIES)
  private List<CapabilitiesEnum> capabilities = new ArrayList<>();

  public static final String SERIALIZED_NAME_CACHE_TIMEOUT = "cache_timeout";
  @SerializedName(SERIALIZED_NAME_CACHE_TIMEOUT)
  private Integer cacheTimeout;

  public static final String SERIALIZED_NAME_CACHE_TIMEOUT_FLOWS = "cache_timeout_flows";
  @SerializedName(SERIALIZED_NAME_CACHE_TIMEOUT_FLOWS)
  private Integer cacheTimeoutFlows;

  public static final String SERIALIZED_NAME_CACHE_TIMEOUT_POLICIES = "cache_timeout_policies";
  @SerializedName(SERIALIZED_NAME_CACHE_TIMEOUT_POLICIES)
  private Integer cacheTimeoutPolicies;

  public static final String SERIALIZED_NAME_CACHE_TIMEOUT_REPUTATION = "cache_timeout_reputation";
  @SerializedName(SERIALIZED_NAME_CACHE_TIMEOUT_REPUTATION)
  private Integer cacheTimeoutReputation;

  public Config() {
  }

  public Config errorReporting(ErrorReportingConfig errorReporting) {
    this.errorReporting = errorReporting;
    return this;
  }

  /**
   * Get errorReporting
   * @return errorReporting
   */
  @javax.annotation.Nonnull
  public ErrorReportingConfig getErrorReporting() {
    return errorReporting;
  }

  public void setErrorReporting(ErrorReportingConfig errorReporting) {
    this.errorReporting = errorReporting;
  }


  public Config capabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
    return this;
  }

  public Config addCapabilitiesItem(CapabilitiesEnum capabilitiesItem) {
    if (this.capabilities == null) {
      this.capabilities = new ArrayList<>();
    }
    this.capabilities.add(capabilitiesItem);
    return this;
  }

  /**
   * Get capabilities
   * @return capabilities
   */
  @javax.annotation.Nonnull
  public List<CapabilitiesEnum> getCapabilities() {
    return capabilities;
  }

  public void setCapabilities(List<CapabilitiesEnum> capabilities) {
    this.capabilities = capabilities;
  }


  public Config cacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
    return this;
  }

  /**
   * Get cacheTimeout
   * @return cacheTimeout
   */
  @javax.annotation.Nonnull
  public Integer getCacheTimeout() {
    return cacheTimeout;
  }

  public void setCacheTimeout(Integer cacheTimeout) {
    this.cacheTimeout = cacheTimeout;
  }


  public Config cacheTimeoutFlows(Integer cacheTimeoutFlows) {
    this.cacheTimeoutFlows = cacheTimeoutFlows;
    return this;
  }

  /**
   * Get cacheTimeoutFlows
   * @return cacheTimeoutFlows
   */
  @javax.annotation.Nonnull
  public Integer getCacheTimeoutFlows() {
    return cacheTimeoutFlows;
  }

  public void setCacheTimeoutFlows(Integer cacheTimeoutFlows) {
    this.cacheTimeoutFlows = cacheTimeoutFlows;
  }


  public Config cacheTimeoutPolicies(Integer cacheTimeoutPolicies) {
    this.cacheTimeoutPolicies = cacheTimeoutPolicies;
    return this;
  }

  /**
   * Get cacheTimeoutPolicies
   * @return cacheTimeoutPolicies
   */
  @javax.annotation.Nonnull
  public Integer getCacheTimeoutPolicies() {
    return cacheTimeoutPolicies;
  }

  public void setCacheTimeoutPolicies(Integer cacheTimeoutPolicies) {
    this.cacheTimeoutPolicies = cacheTimeoutPolicies;
  }


  public Config cacheTimeoutReputation(Integer cacheTimeoutReputation) {
    this.cacheTimeoutReputation = cacheTimeoutReputation;
    return this;
  }

  /**
   * Get cacheTimeoutReputation
   * @return cacheTimeoutReputation
   */
  @javax.annotation.Nonnull
  public Integer getCacheTimeoutReputation() {
    return cacheTimeoutReputation;
  }

  public void setCacheTimeoutReputation(Integer cacheTimeoutReputation) {
    this.cacheTimeoutReputation = cacheTimeoutReputation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Config config = (Config) o;
    return Objects.equals(this.errorReporting, config.errorReporting) &&
        Objects.equals(this.capabilities, config.capabilities) &&
        Objects.equals(this.cacheTimeout, config.cacheTimeout) &&
        Objects.equals(this.cacheTimeoutFlows, config.cacheTimeoutFlows) &&
        Objects.equals(this.cacheTimeoutPolicies, config.cacheTimeoutPolicies) &&
        Objects.equals(this.cacheTimeoutReputation, config.cacheTimeoutReputation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorReporting, capabilities, cacheTimeout, cacheTimeoutFlows, cacheTimeoutPolicies, cacheTimeoutReputation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Config {\n");
    sb.append("    errorReporting: ").append(toIndentedString(errorReporting)).append("\n");
    sb.append("    capabilities: ").append(toIndentedString(capabilities)).append("\n");
    sb.append("    cacheTimeout: ").append(toIndentedString(cacheTimeout)).append("\n");
    sb.append("    cacheTimeoutFlows: ").append(toIndentedString(cacheTimeoutFlows)).append("\n");
    sb.append("    cacheTimeoutPolicies: ").append(toIndentedString(cacheTimeoutPolicies)).append("\n");
    sb.append("    cacheTimeoutReputation: ").append(toIndentedString(cacheTimeoutReputation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("error_reporting");
    openapiFields.add("capabilities");
    openapiFields.add("cache_timeout");
    openapiFields.add("cache_timeout_flows");
    openapiFields.add("cache_timeout_policies");
    openapiFields.add("cache_timeout_reputation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("error_reporting");
    openapiRequiredFields.add("capabilities");
    openapiRequiredFields.add("cache_timeout");
    openapiRequiredFields.add("cache_timeout_flows");
    openapiRequiredFields.add("cache_timeout_policies");
    openapiRequiredFields.add("cache_timeout_reputation");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Config
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Config.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Config is not found in the empty JSON string", Config.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Config.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Config` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Config.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `error_reporting`
      ErrorReportingConfig.validateJsonElement(jsonObj.get("error_reporting"));
      // ensure the required json array is present
      if (jsonObj.get("capabilities") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("capabilities").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `capabilities` to be an array in the JSON string but got `%s`", jsonObj.get("capabilities").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Config.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Config' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Config> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Config.class));

       return (TypeAdapter<T>) new TypeAdapter<Config>() {
           @Override
           public void write(JsonWriter out, Config value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Config read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Config given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Config
   * @throws IOException if the JSON string is invalid with respect to Config
   */
  public static Config fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Config.class);
  }

  /**
   * Convert an instance of Config to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

