/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ChallengeChoices;
import org.openapitools.client.model.ContextualFlowInfo;
import org.openapitools.client.model.ErrorDetail;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Challenge shown to the user in identification stage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-25T23:12:57.050901581-03:00[America/Argentina/Cordoba]", comments = "Generator version: 7.8.0")
public class PlexAuthenticationChallenge {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private ChallengeChoices type;

  public static final String SERIALIZED_NAME_FLOW_INFO = "flow_info";
  @SerializedName(SERIALIZED_NAME_FLOW_INFO)
  private ContextualFlowInfo flowInfo;

  public static final String SERIALIZED_NAME_COMPONENT = "component";
  @SerializedName(SERIALIZED_NAME_COMPONENT)
  private String component = "ak-source-plex";

  public static final String SERIALIZED_NAME_RESPONSE_ERRORS = "response_errors";
  @SerializedName(SERIALIZED_NAME_RESPONSE_ERRORS)
  private Map<String, List<ErrorDetail>> responseErrors = new HashMap<>();

  public static final String SERIALIZED_NAME_CLIENT_ID = "client_id";
  @SerializedName(SERIALIZED_NAME_CLIENT_ID)
  private String clientId;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  private String slug;

  public PlexAuthenticationChallenge() {
  }

  public PlexAuthenticationChallenge type(ChallengeChoices type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  public ChallengeChoices getType() {
    return type;
  }

  public void setType(ChallengeChoices type) {
    this.type = type;
  }


  public PlexAuthenticationChallenge flowInfo(ContextualFlowInfo flowInfo) {
    this.flowInfo = flowInfo;
    return this;
  }

  /**
   * Get flowInfo
   * @return flowInfo
   */
  @javax.annotation.Nullable
  public ContextualFlowInfo getFlowInfo() {
    return flowInfo;
  }

  public void setFlowInfo(ContextualFlowInfo flowInfo) {
    this.flowInfo = flowInfo;
  }


  public PlexAuthenticationChallenge component(String component) {
    this.component = component;
    return this;
  }

  /**
   * Get component
   * @return component
   */
  @javax.annotation.Nullable
  public String getComponent() {
    return component;
  }

  public void setComponent(String component) {
    this.component = component;
  }


  public PlexAuthenticationChallenge responseErrors(Map<String, List<ErrorDetail>> responseErrors) {
    this.responseErrors = responseErrors;
    return this;
  }

  public PlexAuthenticationChallenge putResponseErrorsItem(String key, List<ErrorDetail> responseErrorsItem) {
    if (this.responseErrors == null) {
      this.responseErrors = new HashMap<>();
    }
    this.responseErrors.put(key, responseErrorsItem);
    return this;
  }

  /**
   * Get responseErrors
   * @return responseErrors
   */
  @javax.annotation.Nullable
  public Map<String, List<ErrorDetail>> getResponseErrors() {
    return responseErrors;
  }

  public void setResponseErrors(Map<String, List<ErrorDetail>> responseErrors) {
    this.responseErrors = responseErrors;
  }


  public PlexAuthenticationChallenge clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

  /**
   * Get clientId
   * @return clientId
   */
  @javax.annotation.Nonnull
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }


  public PlexAuthenticationChallenge slug(String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  public String getSlug() {
    return slug;
  }

  public void setSlug(String slug) {
    this.slug = slug;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlexAuthenticationChallenge plexAuthenticationChallenge = (PlexAuthenticationChallenge) o;
    return Objects.equals(this.type, plexAuthenticationChallenge.type) &&
        Objects.equals(this.flowInfo, plexAuthenticationChallenge.flowInfo) &&
        Objects.equals(this.component, plexAuthenticationChallenge.component) &&
        Objects.equals(this.responseErrors, plexAuthenticationChallenge.responseErrors) &&
        Objects.equals(this.clientId, plexAuthenticationChallenge.clientId) &&
        Objects.equals(this.slug, plexAuthenticationChallenge.slug);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, flowInfo, component, responseErrors, clientId, slug);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlexAuthenticationChallenge {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    flowInfo: ").append(toIndentedString(flowInfo)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    responseErrors: ").append(toIndentedString(responseErrors)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("flow_info");
    openapiFields.add("component");
    openapiFields.add("response_errors");
    openapiFields.add("client_id");
    openapiFields.add("slug");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("type");
    openapiRequiredFields.add("client_id");
    openapiRequiredFields.add("slug");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PlexAuthenticationChallenge
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PlexAuthenticationChallenge.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PlexAuthenticationChallenge is not found in the empty JSON string", PlexAuthenticationChallenge.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PlexAuthenticationChallenge.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PlexAuthenticationChallenge` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PlexAuthenticationChallenge.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `type`
      ChallengeChoices.validateJsonElement(jsonObj.get("type"));
      // validate the optional field `flow_info`
      if (jsonObj.get("flow_info") != null && !jsonObj.get("flow_info").isJsonNull()) {
        ContextualFlowInfo.validateJsonElement(jsonObj.get("flow_info"));
      }
      if ((jsonObj.get("component") != null && !jsonObj.get("component").isJsonNull()) && !jsonObj.get("component").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `component` to be a primitive type in the JSON string but got `%s`", jsonObj.get("component").toString()));
      }
      if (!jsonObj.get("client_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `client_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("client_id").toString()));
      }
      if (!jsonObj.get("slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PlexAuthenticationChallenge.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PlexAuthenticationChallenge' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PlexAuthenticationChallenge> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PlexAuthenticationChallenge.class));

       return (TypeAdapter<T>) new TypeAdapter<PlexAuthenticationChallenge>() {
           @Override
           public void write(JsonWriter out, PlexAuthenticationChallenge value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PlexAuthenticationChallenge read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PlexAuthenticationChallenge given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PlexAuthenticationChallenge
   * @throws IOException if the JSON string is invalid with respect to PlexAuthenticationChallenge
   */
  public static PlexAuthenticationChallenge fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PlexAuthenticationChallenge.class);
  }

  /**
   * Convert an instance of PlexAuthenticationChallenge to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

