/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ProxyMode
 */
@JsonAdapter(ProxyMode.Adapter.class)
public enum ProxyMode {
  
  PROXY("proxy"),
  
  FORWARD_SINGLE("forward_single"),
  
  FORWARD_DOMAIN("forward_domain");

  private String value;

  ProxyMode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProxyMode fromValue(String value) {
    for (ProxyMode b : ProxyMode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ProxyMode> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProxyMode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProxyMode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProxyMode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ProxyMode.fromValue(value);
  }
}

