/*
 * authentik
 * Making authentication simple.
 *
 * The version of the OpenAPI document: 2024.6.3
 * Contact: hello@goauthentik.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.FlowSetRequest;
import org.openapitools.client.model.UserCreationModeEnum;
import org.openapitools.client.model.UserTypeEnum;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UserWriteStage Serializer
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-25T23:12:57.050901581-03:00[America/Argentina/Cordoba]", comments = "Generator version: 7.8.0")
public class UserWriteStageRequest {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_FLOW_SET = "flow_set";
  @SerializedName(SERIALIZED_NAME_FLOW_SET)
  private List<FlowSetRequest> flowSet = new ArrayList<>();

  public static final String SERIALIZED_NAME_USER_CREATION_MODE = "user_creation_mode";
  @SerializedName(SERIALIZED_NAME_USER_CREATION_MODE)
  private UserCreationModeEnum userCreationMode;

  public static final String SERIALIZED_NAME_CREATE_USERS_AS_INACTIVE = "create_users_as_inactive";
  @SerializedName(SERIALIZED_NAME_CREATE_USERS_AS_INACTIVE)
  private Boolean createUsersAsInactive;

  public static final String SERIALIZED_NAME_CREATE_USERS_GROUP = "create_users_group";
  @SerializedName(SERIALIZED_NAME_CREATE_USERS_GROUP)
  private UUID createUsersGroup;

  public static final String SERIALIZED_NAME_USER_TYPE = "user_type";
  @SerializedName(SERIALIZED_NAME_USER_TYPE)
  private UserTypeEnum userType;

  public static final String SERIALIZED_NAME_USER_PATH_TEMPLATE = "user_path_template";
  @SerializedName(SERIALIZED_NAME_USER_PATH_TEMPLATE)
  private String userPathTemplate;

  public UserWriteStageRequest() {
  }

  public UserWriteStageRequest name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public UserWriteStageRequest flowSet(List<FlowSetRequest> flowSet) {
    this.flowSet = flowSet;
    return this;
  }

  public UserWriteStageRequest addFlowSetItem(FlowSetRequest flowSetItem) {
    if (this.flowSet == null) {
      this.flowSet = new ArrayList<>();
    }
    this.flowSet.add(flowSetItem);
    return this;
  }

  /**
   * Get flowSet
   * @return flowSet
   */
  @javax.annotation.Nullable
  public List<FlowSetRequest> getFlowSet() {
    return flowSet;
  }

  public void setFlowSet(List<FlowSetRequest> flowSet) {
    this.flowSet = flowSet;
  }


  public UserWriteStageRequest userCreationMode(UserCreationModeEnum userCreationMode) {
    this.userCreationMode = userCreationMode;
    return this;
  }

  /**
   * Get userCreationMode
   * @return userCreationMode
   */
  @javax.annotation.Nullable
  public UserCreationModeEnum getUserCreationMode() {
    return userCreationMode;
  }

  public void setUserCreationMode(UserCreationModeEnum userCreationMode) {
    this.userCreationMode = userCreationMode;
  }


  public UserWriteStageRequest createUsersAsInactive(Boolean createUsersAsInactive) {
    this.createUsersAsInactive = createUsersAsInactive;
    return this;
  }

  /**
   * When set, newly created users are inactive and cannot login.
   * @return createUsersAsInactive
   */
  @javax.annotation.Nullable
  public Boolean getCreateUsersAsInactive() {
    return createUsersAsInactive;
  }

  public void setCreateUsersAsInactive(Boolean createUsersAsInactive) {
    this.createUsersAsInactive = createUsersAsInactive;
  }


  public UserWriteStageRequest createUsersGroup(UUID createUsersGroup) {
    this.createUsersGroup = createUsersGroup;
    return this;
  }

  /**
   * Optionally add newly created users to this group.
   * @return createUsersGroup
   */
  @javax.annotation.Nullable
  public UUID getCreateUsersGroup() {
    return createUsersGroup;
  }

  public void setCreateUsersGroup(UUID createUsersGroup) {
    this.createUsersGroup = createUsersGroup;
  }


  public UserWriteStageRequest userType(UserTypeEnum userType) {
    this.userType = userType;
    return this;
  }

  /**
   * Get userType
   * @return userType
   */
  @javax.annotation.Nullable
  public UserTypeEnum getUserType() {
    return userType;
  }

  public void setUserType(UserTypeEnum userType) {
    this.userType = userType;
  }


  public UserWriteStageRequest userPathTemplate(String userPathTemplate) {
    this.userPathTemplate = userPathTemplate;
    return this;
  }

  /**
   * Get userPathTemplate
   * @return userPathTemplate
   */
  @javax.annotation.Nullable
  public String getUserPathTemplate() {
    return userPathTemplate;
  }

  public void setUserPathTemplate(String userPathTemplate) {
    this.userPathTemplate = userPathTemplate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserWriteStageRequest userWriteStageRequest = (UserWriteStageRequest) o;
    return Objects.equals(this.name, userWriteStageRequest.name) &&
        Objects.equals(this.flowSet, userWriteStageRequest.flowSet) &&
        Objects.equals(this.userCreationMode, userWriteStageRequest.userCreationMode) &&
        Objects.equals(this.createUsersAsInactive, userWriteStageRequest.createUsersAsInactive) &&
        Objects.equals(this.createUsersGroup, userWriteStageRequest.createUsersGroup) &&
        Objects.equals(this.userType, userWriteStageRequest.userType) &&
        Objects.equals(this.userPathTemplate, userWriteStageRequest.userPathTemplate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, flowSet, userCreationMode, createUsersAsInactive, createUsersGroup, userType, userPathTemplate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserWriteStageRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    flowSet: ").append(toIndentedString(flowSet)).append("\n");
    sb.append("    userCreationMode: ").append(toIndentedString(userCreationMode)).append("\n");
    sb.append("    createUsersAsInactive: ").append(toIndentedString(createUsersAsInactive)).append("\n");
    sb.append("    createUsersGroup: ").append(toIndentedString(createUsersGroup)).append("\n");
    sb.append("    userType: ").append(toIndentedString(userType)).append("\n");
    sb.append("    userPathTemplate: ").append(toIndentedString(userPathTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("flow_set");
    openapiFields.add("user_creation_mode");
    openapiFields.add("create_users_as_inactive");
    openapiFields.add("create_users_group");
    openapiFields.add("user_type");
    openapiFields.add("user_path_template");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("name");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UserWriteStageRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UserWriteStageRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UserWriteStageRequest is not found in the empty JSON string", UserWriteStageRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UserWriteStageRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UserWriteStageRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UserWriteStageRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("flow_set") != null && !jsonObj.get("flow_set").isJsonNull()) {
        JsonArray jsonArrayflowSet = jsonObj.getAsJsonArray("flow_set");
        if (jsonArrayflowSet != null) {
          // ensure the json data is an array
          if (!jsonObj.get("flow_set").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `flow_set` to be an array in the JSON string but got `%s`", jsonObj.get("flow_set").toString()));
          }

          // validate the optional field `flow_set` (array)
          for (int i = 0; i < jsonArrayflowSet.size(); i++) {
            FlowSetRequest.validateJsonElement(jsonArrayflowSet.get(i));
          };
        }
      }
      // validate the optional field `user_creation_mode`
      if (jsonObj.get("user_creation_mode") != null && !jsonObj.get("user_creation_mode").isJsonNull()) {
        UserCreationModeEnum.validateJsonElement(jsonObj.get("user_creation_mode"));
      }
      if ((jsonObj.get("create_users_group") != null && !jsonObj.get("create_users_group").isJsonNull()) && !jsonObj.get("create_users_group").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `create_users_group` to be a primitive type in the JSON string but got `%s`", jsonObj.get("create_users_group").toString()));
      }
      // validate the optional field `user_type`
      if (jsonObj.get("user_type") != null && !jsonObj.get("user_type").isJsonNull()) {
        UserTypeEnum.validateJsonElement(jsonObj.get("user_type"));
      }
      if ((jsonObj.get("user_path_template") != null && !jsonObj.get("user_path_template").isJsonNull()) && !jsonObj.get("user_path_template").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `user_path_template` to be a primitive type in the JSON string but got `%s`", jsonObj.get("user_path_template").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UserWriteStageRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UserWriteStageRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UserWriteStageRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UserWriteStageRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UserWriteStageRequest>() {
           @Override
           public void write(JsonWriter out, UserWriteStageRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UserWriteStageRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UserWriteStageRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UserWriteStageRequest
   * @throws IOException if the JSON string is invalid with respect to UserWriteStageRequest
   */
  public static UserWriteStageRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UserWriteStageRequest.class);
  }

  /**
   * Convert an instance of UserWriteStageRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

